---

- name: Systemd | Configuration
  template:
    src: "{{ item }}"
    dest: "/etc/{{ item | replace('.j2', '') }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - systemd/journald.conf.j2
